# -*- coding: utf-8 -*-
"""
install_root_router.py
======================

Optional Pythonista root-router installer for public Forge.

Run this file manually from inside a Forge install when you want tappable
LinkOS console links and root-launcher mode.

It writes small launcher scripts at Pythonista Documents root:

    forge_entry.py
    linkos.py

Those launchers route into this Forge install. Existing root launchers are
backed up first.

This is a power upgrade: Forge can operate from the wider Pythonista
Documents workspace after installation. Only run it deliberately.
"""

from __future__ import print_function

import datetime
import os
import shutil


HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.abspath(os.path.expanduser('~/Documents'))
STAMP = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
BACKUP_DIR = os.path.join(DOCS, 'archive', 'forge_root_router_before_' + STAMP)

MARKER = 'FORGE_ROOT_ROUTER'


def _ensure_dir(path):
    if path and not os.path.isdir(path):
        os.makedirs(path)


def _backup_existing(name):
    src = os.path.join(DOCS, name)
    if not os.path.exists(src):
        return ''
    _ensure_dir(BACKUP_DIR)
    dst = os.path.join(BACKUP_DIR, name)
    shutil.copy2(src, dst)
    return dst


def _write(path, text):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)


def _launcher_common():
    return """# -*- coding: utf-8 -*-
# {marker}
# Auto-generated by install_root_router.py.
# Routes Pythonista root launcher calls into a specific Forge install.

import os
import runpy
import sys

FORGE_INSTALL = {install!r}

# Root-router launches from ~/Documents, where a lowercase forge/ folder can
# shadow the contained public install. Force this install to the very front.
try:
    while FORGE_INSTALL in sys.path:
        sys.path.remove(FORGE_INSTALL)
except Exception:
    pass
sys.path.insert(0, FORGE_INSTALL)

os.environ['FORGE_ROOT_LAUNCHER'] = '1'
os.environ['FORGE_INSTALL_ROOT'] = FORGE_INSTALL


def _evict_forge_modules():
    \"\"\"Evict cached Forge modules so root-router launches use FORGE_INSTALL.

    Pythonista can keep modules alive between runs. If an older/root-level
    forge package was imported earlier, merely changing sys.path is not enough:
    Python will reuse the cached package. Root-router launches must be
    deterministic, so clear forge and all forge.* modules before dispatch.
    \"\"\"
    stale = [
        name for name in list(sys.modules.keys())
        if name == 'forge' or name.startswith('forge.')
    ]
    for name in stale:
        try:
            del sys.modules[name]
        except Exception:
            pass
""".format(marker=MARKER, install=HERE)


def _forge_entry_text():
    return _launcher_common() + """

TARGET = os.path.join(FORGE_INSTALL, 'forge_entry.py')

if __name__ == '__main__':
    _evict_forge_modules()
    runpy.run_path(TARGET, run_name='__main__')
"""


def _linkos_text():
    return _launcher_common() + """

def main(argv=None):
    _evict_forge_modules()

    from forge.extensions.linkos.router import dispatch

    args = sys.argv[1:] if argv is None else (argv or [])
    if not args:
        args = ['start-here']
    dispatch(args)


if __name__ == '__main__':
    main()
"""


def install():
    print('=== INSTALL FORGE ROOT ROUTER ===')
    print('Forge install:', HERE)
    print('Documents root:', DOCS)
    print('')

    for required in ('forge', 'forge_entry.py', 'linkos.py'):
        path = os.path.join(HERE, required)
        if not os.path.exists(path):
            print('ERROR: missing required install file:', required)
            return False

    backed = []
    for name in ('forge_entry.py', 'linkos.py'):
        b = _backup_existing(name)
        if b:
            backed.append(b)

    _write(os.path.join(DOCS, 'forge_entry.py'), _forge_entry_text())
    _write(os.path.join(DOCS, 'linkos.py'), _linkos_text())

    print('Installed root launchers:')
    print('- forge_entry.py')
    print('- linkos.py')
    print('')

    if backed:
        print('Backed up previous launchers to:')
        print(BACKUP_DIR)
        print('')

    print('Root-router mode is now available.')
    print('')
    print('Benefits:')
    print('- tappable LinkOS console links')
    print('- easier Shortcut launch')
    print('- wider Pythonista Documents workspace access')
    print('')
    print('Risk:')
    print('- Forge can inspect and patch more of your workspace.')
    print('- Keep trusting the run packet and inspect before editing.')
    print('')
    print('Next:')
    print('1. Run forge_entry.py from Pythonista Documents root.')
    print('2. Run DOCS OPEN onboarding or HELP LINKOS.')
    return True


if __name__ == '__main__':
    install()
